declare global {
  interface Window {
    electronAPI: {
      chatSend: (data: string | { message: string; threadId?: string }) => void;
      onChatChunk: (callback: (data: string) => void) => () => void;
      onChatDone: (callback: () => void) => () => void;
      onChatError: (callback: (err: string) => void) => () => void;
      cancelChat: () => Promise<{ success: boolean }>;
      hideWindow: () => void;
      minimizeWindow: () => void;
      quitApp: () => void;
      resizeWindow: (width: number, height: number) => void;
      platform: string;
      configGet: (key: string) => Promise<any>;
      configSet: (key: string, value: any) => Promise<{ success: boolean; error?: string }>;
      configDelete: (key: string) => Promise<{ success: boolean; error?: string }>;
      configGetAll: () => Promise<Record<string, any>>;
      onConfigChanged: (callback: (key: string) => void) => () => void;
      invokeProviderPresets: () => Promise<any[]>;
      testProviderConnectivity: (config: any) => Promise<{ success: boolean; error?: string; latency?: number }>;
      fetchProviderModels: (config: any) => Promise<{ success: boolean; models?: any[]; error?: string }>;
      testModelAvailability: (config: any, modelId: string) => Promise<{ success: boolean; error?: string; response?: string; latency?: number }>;
      createThread: (title?: string) => Promise<{ id: string; title: string; resourceId: string; createdAt: string; updatedAt: string }>;
      listThreads: () => Promise<Array<{ id: string; title: string; resourceId: string; createdAt: string; updatedAt: string }>>;
      getThread: (threadId: string) => Promise<{ id: string; title: string; resourceId: string; createdAt: string; updatedAt: string } | null>;
      deleteThread: (threadId: string) => Promise<boolean>;
      getThreadMessages: (threadId: string) => Promise<any[]>;
      getWorkingMemory: () => Promise<string | null>;
      clearWorkingMemory: () => Promise<{ success: boolean; error?: string }>;
      getCapabilities: () => Promise<Array<{ id: string; name: string; description: string; category: string }>>;
      getAgentsList: () => Promise<Array<{ id: string; name: string; description: string }>>;
      getModels: () => Promise<Array<{ id: string; modelId: string; provider: string }>>;
      getActiveModel: () => Promise<string | null>;
      setActiveModel: (modelString: string, providerConfig?: { providerType: string; baseUrl: string; apiKey: string }) => Promise<{ success: boolean }>;
      getModelCapabilities: (modelId: string) => Promise<{ vision: boolean; contextLength: number; known: boolean }>;
      getModelDisplayName: (modelId: string) => Promise<string | null>;
      getCapabilitiesWithOverride: (modelId: string) => Promise<{ vision: boolean; contextLength: number; known: boolean }>;
      getSystemVersion: () => Promise<{ version: string; electron: string; node: string; chrome: string }>;
      selectDirectory: () => Promise<string | null>;
      moveDataDir: (newDir: string) => Promise<{ success: boolean; error?: string }>;
      knowledgeStatus: () => Promise<{ configured: boolean; mode: 'remote' | 'local'; baseUrl?: string; localReady?: boolean }>;
      knowledgeSetMode: (mode: 'remote' | 'local') => Promise<{ success: boolean }>;
      knowledgeLoadModel: () => Promise<{ success: boolean; ready?: boolean; error?: string }>;
      knowledgeModelStatus: () => Promise<{ ready: boolean; downloading: boolean; progress: number; modelPath: string }>;
      knowledgeDeleteModel: () => Promise<{ success: boolean; error?: string }>;
      knowledgeIngest: (name: string, text: string, taskId?: string) => Promise<{ success: boolean; docId?: string; chunks?: number; error?: string }>;
      knowledgeIngestFile: () => Promise<{ success: boolean; files?: Array<{ path: string; name: string; size: number; tooLarge: boolean }>; error?: string }>;
      knowledgeIngestFilePath: (filePath: string, name: string, taskId?: string) => Promise<{ success: boolean; docId?: string; chunks?: number; error?: string }>;
      onKnowledgeIngestProgress: (callback: (taskId: string, progress: number) => void) => () => void;
      knowledgeQuery: (query: string, topK?: number) => Promise<{ success: boolean; results?: Array<{ id: string; score: number; metadata: Record<string, any> }>; error?: string }>;
      knowledgeList: () => Promise<{ success: boolean; documents: Array<{ docId: string; name: string; date: string; chunkCount: number }>; error?: string }>;
      knowledgeDelete: (docId: string) => Promise<{ success: boolean; error?: string }>;
      automationRun: (name: string, desc: string, trigger: string) => Promise<{ success: boolean; status?: string; output?: string; timestamp?: string; error?: string }>;
      automationListWorkflows: () => Promise<{ success: boolean; workflows: Array<{ id: string; name: string }>; error?: string }>;
      automationHistory: () => Promise<Array<{ name: string; desc: string; trigger: string; success: boolean; status?: string; output?: string; timestamp: string; ts: string }>>;
      diagSetLogging: (enabled: boolean) => Promise<{ enabled: boolean }>;
      diagGetLoggingState: () => Promise<{ enabled: boolean }>;
      diagGetLogs: () => Promise<Array<{ ts: string; level: string; source: string; message: string }>>;
      diagClearLogs: () => Promise<boolean>;
      diagSubscribe: () => Promise<boolean>;
      diagUnsubscribe: () => Promise<boolean>;
      testTool: (toolId: string, userArgs?: Record<string, any>) => Promise<{ success: boolean; output: any; duration: number; error?: string }>;
      getToolInputFields: (toolId: string) => Promise<Array<{ name: string; type: 'string' | 'boolean' | 'number' | 'enum'; required: boolean; description: string; defaultVal: any; enumOptions?: string[] }>>;
      speechAvailable: () => Promise<boolean>;
      speechStart: (timeoutSec?: number) => Promise<{ started: boolean; error?: string }>;
      speechStop: () => Promise<{ stopped: boolean }>;
      speechRecognize: (timeoutSec?: number) => Promise<{ success: boolean; confidence: number; text: string }>;
      onSpeechPartial: (cb: (data: { confidence: number; text: string }) => void) => () => void;
      onSpeechResult: (cb: (data: { success: boolean; confidence: number; text: string }) => void) => () => void;
      onSpeechDone: (cb: () => void) => () => void;
      onSpeechError: (cb: (err: string) => void) => () => void;
      shortcutsGet: () => Promise<{ commandBar: string; newSession: string; hideWindow: string }>;
      shortcutsSet: (shortcuts: Partial<{ commandBar: string; newSession: string; hideWindow: string }>) => Promise<{ success: boolean }>;
      onShortcutNewSession: (cb: (threadId: string) => void) => () => void;
      openExternal: (url: string) => Promise<boolean>;
      getDefaultDataDir: () => Promise<string>;
      getMemoryConfig: () => Promise<{
        lastMessages: number;
        semanticRecall: boolean;
        semanticTopK: number;
        semanticMessageRange: number;
        workingMemory: boolean;
        generateTitle: boolean;
        compressAlgorithm: string;
        compressThreshold: number;
        systemPrompt: string;
        maxSteps: number;
        temperature: number;
        knowledgeAutoRetrieve: boolean;
        knowledgeTopK: number;
        knowledgeScoreThreshold: number;
      }>;
      setMemoryConfig: (config: {
        lastMessages: number;
        semanticRecall: boolean;
        semanticTopK: number;
        semanticMessageRange: number;
        workingMemory: boolean;
        generateTitle: boolean;
        compressAlgorithm: string;
        compressThreshold: number;
        systemPrompt?: string;
        maxSteps?: number;
        temperature?: number;
        knowledgeAutoRetrieve?: boolean;
        knowledgeTopK?: number;
        knowledgeScoreThreshold?: number;
      }) => Promise<{ success: boolean }>;
      onKnowledgeDownloadProgress: (cb: (progress: number, status: string) => void) => () => void;
    };
  }
}
